[build]
publish = "build/"
command = "npm run build"

[[headers]]
for = "/*"
[headers.values]
# Content-Security-Policy = "default-src 'self';  img-src: 'self' blob: data:;  style-src 'self' 'unsafe-inline';  script-src 'self' 'unsafe-inline' 'unsafe-eval'  unpkg.com;"
X-Frame-Options = "SAMEORIGIN"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "no-referrer"
Permissions-Policy = "geolocation=(self)"
