[dev]
framework = "svelte-kit"
command = "svelte-kit dev"

[build]
publish = "build/"
command = "npm run build"


[[headers]]
for = "/*"

[headers.values]
# Content-Security-Policy = "default-src 'self';"
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "no-referrer"
Permissions-Policy = "geolocation=(self)"

[[redirects]]
from = "/img/*"
to = "/.netlify/builders/img"
status = 200

[[redirects]]
from = "api/submitForm"
to = "/.netlify/functions/submitForm"
status = 200

[functions]
node_bundler = "esbuild"
