[dev]
framework = "svelte-kit"
command = "svelte-kit dev"


[build]
publish = "build/"
command = "npm run build"


[[headers]]
for = "/*"

[headers.values]
Content-Security-Policy = "default-src 'self';  style-src 'self' 'unsafe-inline';  script-src 'self' 'unsafe-inline' 'unsafe-eval'; connect-src *;"
X-Frame-Options = "SAMEORIGIN"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "no-referrer"
Permissions-Policy = "geolocation=(self)"

[context.production]
Content-Security-Policy = "default-src 'self';  style-src 'self' 'unsafe-inline';  script-src 'self' 'unsafe-inline' 'unsafe-eval'; ws"


[[redirects]]
from = "/img/*"
to = "/.netlify/builders/img"
status = 200


[functions]
node_bundler = "esbuild"
